# Generated by Django 3.1.2 on 2020-10-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '보더콜리단 태그', 'verbose_name_plural': '보더콜리단 태그'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='fastcampus_tag',
        ),
    ]
