# Generated by Django 3.1.2 on 2020-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fc_user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
