# Generated by Django 3.1.2 on 2020-10-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '보더콜리단 게시글', 'verbose_name_plural': '보더콜리단 게시글'},
        ),
        migrations.AlterModelTable(
            name='board',
            table='fastcampus_fc_board',
        ),
    ]
